#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
题目 11 · 为美好的密码献上解密  (0xGame 2026, Crypto, 1000)

服务: nc1.ctfplus.cn:34032

协议
----
=== CTF 环境 ... ===
[+] curve = NIST521p      (secp521r1)
[+] hash  = sha512
[+] public_key: <PEM>
[+] hint: k is generated by Linear_Feedback_shift_resgister_of_length_five
How many signatures do you want? 1-60: <n>        # n 必须 >= 32 才进入下一阶段
  [i] msg = <32 hex>  r = ...  s = ...            # 共 n 条
Have you decrypted successfully? (y/n): y
[+] Then sign this message for me.
message = the treasure lies hidden within the mirror
[+] The r is fixed.
r = 2661740802...5999846            # == x(G) !!
s = <在这里输入 DECIMAL>

漏洞
----
1) k 来自 length-5 LFSR -> k 序列周期恰为 31。因此 r_(i+31) == r_i（非随机！
   60 条签名里 29 对重复 r）。同一 k 签两条不同消息:
        s_i = k^-1 (h_i + r d)
        s_j = k^-1 (h_j + r d)
   =>   k = (h_i - h_j) * (s_i - s_j)^-1 mod n
        d = (s_i k - h_i) * r^-1 mod n
   哈希口径: h = int(sha512(<msg 的 ASCII hex 字符串>))   (不是 raw bytes!)

2) 最后阶段的固定 r 正好等于 Gx = x(G)，即 k = 1 或 k = n-1。
   服务用的是 k = n-1（R = -G），故
        s = (n-1)^-1 (h + r d) = -(h + r d) mod n

坑
--
* 服务用 int(input()) 解析 s —— **十进制**！发 hex（含 a-f）会抛异常回 "bye"，
  只有纯数字的 hex（如 2^200）才会被当成数字继续走验证，极易误判。
* 提交要 s 的整数值，不要 0x 前缀、不要补零。
"""

import hashlib
import base64
import re
import sys
from collections import defaultdict

from pwn import remote, context
from cryptography.hazmat.primitives.serialization import load_pem_public_key

context.log_level = "error"

HOST, PORT = "nc1.ctfplus.cn", 34032

# ---- secp521r1 (p = 2^521 - 1, 梅森素数) ----
p = 2**521 - 1
n = 0x01FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA51868783BF2F966B7FCC0148F709A5D03BB5C9B8899C47AEBB6FB71E91386409
a = p - 3
Gx = 0x00C6858E06B70404E9CD9E3ECB662395B4429C648139053FB521F828AF606B4D3DBAA14B5E77EFE75928FE1DC127A2FFA8DE3348B3C1856A429BF97E7E31C2E5BD66
Gy = 0x011839296A789A3BC0045C8A5FB42C7D1BD998F54449579B446817AFBD17273E662C97EE72995EF42640C550B9013FAD0761353C7086A272C24088BE94769FD16650
G = (Gx, Gy)


def inv(x, m):
    return pow(x, -1, m)


def add(P, Q):
    if P is None:
        return Q
    if Q is None:
        return P
    x1, y1 = P
    x2, y2 = Q
    if x1 == x2 and (y1 + y2) % p == 0:
        return None
    if P == Q:
        lam = (3 * x1 * x1 + a) * inv(2 * y1, p) % p
    else:
        lam = (y2 - y1) * inv(x2 - x1, p) % p
    x3 = (lam * lam - x1 - x2) % p
    return (x3, (lam * (x1 - x3) - y1) % p)


def mul(k, P):
    R = None
    while k:
        if k & 1:
            R = add(R, P)
        P = add(P, P)
        k >>= 1
    return R


# 题目服务签名时: msg 以 ASCII hex 字符串形式被 sha512
def h_of(msg_ascii_hex: str) -> int:
    return int.from_bytes(hashlib.sha512(msg_ascii_hex.encode()).digest(), "big")


def recv_sigs(count=32):
    io = remote(HOST, PORT)
    banner = io.recvuntil(b"1-60: ", timeout=25).decode(errors="replace")
    io.sendline(str(count).encode())
    body = io.recvuntil(b"(y/n): ", timeout=40).decode(errors="replace")
    sigs = re.findall(r"\[\d+\]\s*\nmsg = ([0-9a-f]+)\nr = (\d+)\ns = (\d+)", body)
    sigs = [(m, int(r), int(s)) for m, r, s in sigs]
    assert len(sigs) == count, f"got {len(sigs)} sigs"
    return io, banner, sigs


def parse_pubkey(banner):
    pem = re.search(
        r"-----BEGIN PUBLIC KEY-----.*?-----END PUBLIC KEY-----", banner, re.S
    ).group(0)
    pn = load_pem_public_key(pem.encode()).public_numbers()
    return (pn.x, pn.y), pem


def recover_d(sigs, Q):
    """同一 k 在 i 与 i+31 复用 -> 直接解出 k 与 d。"""
    by_r = defaultdict(list)
    for i, (_, r, _) in enumerate(sigs):
        by_r[r].append(i)
    pairs = [v for v in by_r.values() if len(v) > 1]
    assert pairs, "no repeated r -> LFSR seed not continuous?"
    for i, j in pairs:
        hi, hj = h_of(sigs[i][0]), h_of(sigs[j][0])
        for sgn in (1, -1):  # k_j = sgn * k_i
            den = (sigs[i][2] - sgn * sigs[j][2]) % n
            if den == 0:
                continue
            k = ((hi - hj) * inv(den, n)) % n
            if k == 0:
                continue
            d = ((sigs[i][2] * k - hi) * inv(sigs[i][1], n)) % n
            if mul(d, G) == Q:
                return d, k, (i, j)
    raise RuntimeError("d recovery failed")


def main():
    io, banner, sigs = recv_sigs(32)
    Q, _ = parse_pubkey(banner)
    d, k_recovered, pair = recover_d(sigs, Q)
    print(f"[+] nonce-reuse pair {pair}, k = {hex(k_recovered)[:24]}...")
    print(f"[+] private key d = {hex(d)}")

    # 交叉验证: 用 d 反推每条签名的 k, 检查 x(kG) == r
    ok = all(
        (lambda P: P and P[0] == r)(mul(((h_of(m) + r * d) * inv(s, n)) % n, G))
        for m, r, s in sigs
    )
    print(f"[+] d verified on all {len(sigs)} signatures: {ok}")
    assert ok

    # 进入最后阶段
    io.sendline(b"y")
    tail = io.recvuntil(b"s = ", timeout=25).decode(errors="replace")
    msg = re.search(r"message = (.*)", tail).group(1).strip()
    R = int(re.search(r"r = (\d+)", tail).group(1))
    print(f"[+] challenge message = {msg!r}")
    print(f"[+] fixed r == x(G): {R == Gx}  -> k in {{1, n-1}}")

    h = int.from_bytes(hashlib.sha512(msg.encode()).digest(), "big")
    answers = [("k=1", (h + R * d) % n), ("k=n-1", (-(h + R * d)) % n)]
    for name, s in answers:
        io.sendline(str(s).encode())  # 十进制! 服务用 int(input())
        out = io.recv(timeout=10).decode(errors="replace")
        print(f"[*] try {name}: {out.strip()!r}")
        if "0xGame{" in out:
            flag = re.search(r"0xGame\{[^}]*\}", out).group(0)
            print(f"\n[+] FLAG = {flag}")
            io.close()
            return flag
        # 失败后连接会被服务端关闭，需要重连再试另一个 k
        if name == "k=1":
            io, banner, sigs = recv_sigs(32)
            io.sendline(b"y")
            io.recvuntil(b"s = ", timeout=25)
    io.close()
    raise RuntimeError("both k candidates rejected")


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
